version: '3.8'

services:
  bot:
    build: .
    container_name: video-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GDRIVE_JSON=${GDRIVE_JSON}
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
